name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.0

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint src/ tests/

      - name: Run tests
        run: deno test tests/ --allow-net